AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CD4ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codedeploy.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  CD4InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  CD4InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - CD2InstanceRole
      InstanceProfileName: CD5InstanceProfile
  4c:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-a0383dc5
      GroupDescription: 4c
      SecurityGroupIngress:
      -
        CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      -
        CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: oregonkeypair
      SecurityGroupIds:
      - !Ref 4c
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y git
          sudo -u ec2-user bash -c 'cd /home/ec2-user; git clone https://github.com/craigwongva/4b.git'
          sudo -u ec2-user bash -c '/home/ec2-user/4b/userdata'
      InstanceType: t2.micro
      ImageId: ami-32d8124a
      Tags:
        -
          Key: Name
          Value: Dev4
